#!/usr/bin/env bash
# TODO: add support for using lowriter if available


help_and_exit() {
    echo "termdoc uses libreoffice (if available) or the online service doc2pdf"
    echo "to convert and display MS Office files using termpdf"
    echo
    echo "Usage:"
    echo "    termdoc file.docx"
    exit
}

doc2pdf() {
   curl -# -F inputDocument=@"$1" http://www.doc2pdf.net/convert/document.pdf > "${tmp_dir}/${1%.*}.pdf"
}

soffice() {
    $soffice_binary \
        --headless \
        --convert-to pdf \
        --outdir ${tmp_dir} \
        "$1" & 
        # if iTerm is in fullscreen, soffice will steal focus
        sleep .5
        osascript -e 'tell application "iTerm" to activate'
        wait
}

case "$1" in
    *.pdf|*.djvu|*.tif|*.tif)
        termpdf "$1"
        ;;
    *)
        tmp_dir=$(mktemp -d)
        for i in "/Applications/LibreOffice.app/Contents/MacOS/soffice" \
            "$HOME/Applications/LibreOffice.app/Contents/MacOS/soffice" 
        do
            if [[ -x "$i" ]]; then
                soffice_binary="$i"
                use_soffice=true
                soffice "$1"
            fi
        done 
        if [[ -z $use_soffice ]]; then
            doc2pdf "$1"
        fi
        termpdf "${tmp_dir}/${1%.*}.pdf"
        rm -rf $tmp_dir
        exit
        ;;
    *)
        help_and_exit
        ;;
esac

