#!/usr/bin/env bash
# TODO: add support for using lowriter if available


help_and_exit() {
    echo "termdoc is a wrapper around libreoffice and termpdf, for"
    echo "viewing various file formats in your terminal."
    echo
    echo "Usage:"
    echo "    termdoc <options> file.docx"
    echo 
    echo "    options:"
    echo "         -d: use doc2pdf instead of libreoffice"
    echo "             WARNING: DONT USE FOR CONFIDENTIAL DOCS"
    exit
}

doc2pdf() {
   curl -# -F inputDocument=@"$1" http://www.doc2pdf.net/convert/document.pdf > "${tmp_dir}/${1%.*}.pdf"
}

soffice() {
    $soffice_binary \
        --headless \
        --convert-to pdf \
        --outdir ${tmp_dir} \
        "$1" & 
        # if iTerm is in fullscreen, soffice will steal focus
        sleep .5
        osascript -e 'tell application "iTerm" to activate'
        wait
}

if [[ "$1" == "-h" ]]; then
    help_and_exit
fi

if [[ "$1" == "-d" ]]; then
    shift 1
    use_doc2pdf=true
else
    for i in "/Applications/LibreOffice.app/Contents/MacOS/soffice" \
        "$HOME/Applications/LibreOffice.app/Contents/MacOS/soffice" 
    do
        if [[ -x "$i" ]]; then
            soffice_binary="$i"
        fi
    done 
fi

case "$1" in
    *.pdf|*.djvu|*.tif|*.tif)
        termpdf "$1"
        ;;
    *)
        tmp_dir=$(mktemp -d)
        if [[ $use_doc2pdf == "true" ]]; then
            doc2pdf "$1"
        elif [[ -z "$soffice_binary" ]]; then
            echo "LibreOffice not found."
            rm -rf $tmp_dir
            exit
        else
            soffice "$1"
        fi
        termpdf "${tmp_dir}/${1%.*}.pdf"
        rm -rf $tmp_dir
        exit
        ;;
    *)
        help_and_exit
        ;;
esac

